# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Klc91ApQtUdReJbFBr7FxnUz3JWotSF4
"""

! sudo  apt-get -y install libvips

! pip3 install pyvips  chardet

a = '''If in a certain language, MADRAS is coded as NBESBT, how is BOMBAY coded in that code ?
A. CPNCBX		
B. CPNCBZ		
C. CPOCBZ		
D. None of these
++++++++++++++++++
In a certain code, TRIPLE is written as SQHOKD. How is DISPOSE written in that code ?
A. CHRONRD	
B. DSOESPI		
C. ESJTPTF		
D. ESOPSID
++++++++++++++++++
If in a code language, COULD is written as BNTKC and MARGIN is written as LZQFHM, how will MOULDING be written in that code?
A. CHMFINTK	
B. LNKTCHMF		
C. LNTKCHMF		
D. NITKHCMF
++++++++++++++++++
In a certain code, MONKEY is written as XDJMNL. How is TIGER written in that code ?
A. QDFHS		
B. SDFHS		
C. SHFDQ		
D. UJHFS
++++++++++++++++++
If FRAGRANCE is written as SBHSBODFG, how can IMPOSING be written ?
A. NQPTJHOT	
B. NQPTJOHI		
C. NQTPJOHJ		
D. NQPTJOHJ
++++++++++++++++++
In a certain code, COMPUTER is written as RFUVQNPC. How is MEDICINE written in the same code ?
A. EOJDJEFM	
B. EOJDEJFM		
C. MFEJDJOE		
D. MFEDJJOE
++++++++++++++++++
If in a certain language, GAMBLE is coded as FBLCKF , how is FLOWER coded in that code ?
A. GKPVFQ		
B. EMNXDS		
C. GMPVDS		
D. HNQYGT
++++++++++++++++++
If in a certain language, NATURE is coded as MASUGE, how is FAMINE coded in that code ?
A. FBMJND		
B. FZMHND		
C. GANIOE		
D. EALIME
++++++++++++++++++
If in a certain code, TEACHER is written as VGCEJGT, how would DULLARD be written in the same code ?
A. FWMNCTF	
B. FWNNBTE		
C. FWNNCSF		
D. FWNNCTF
++++++++++++++++++
If in a certain language FASHION is coded as FOIHSAN, how is PROBLEM coded in that code ?
A. ROBLEMP	
B. PELBORM		
C. PRBOELM		
D. RPBOELM
++++++++++++++++++
If in a certain language KINDLE is coded as ELDNIK, how is EXOTIC coded in that code ?
A. EXOTLC		
B. CXOTIE		
C. COXITE		
D. CITOXE
++++++++++++++++++
If VICTORY is coded as YLFWRUB, how can SUCCESS be coded ?
A. VXEEIVV		
B. VXFFHVV		
C. VYEEHVV		
D. VYEFIVV
++++++++++++++++++
In a certain code, TOGETHER is written as RQEGRJCT. In the same code, PAROLE will be written as
A. NCPQJG		
B. NCQPJG		
C. RCPQJK		
D. RCTQNG
++++++++++++++++++
If BOMBAY is written as MYMYMY, how will TAMIL NADU be written in that code ?
A. TIATIATIA 	
B. MNUMNUMNU	
C. IATIATIAT		
D. ALDALDALD
++++++++++++++++++
If FRIEND is coded as HUMJTK, how is CANDLE written in that code ?
A. EDRIRL		
B. DCQHQK		
C. ESJFME		
D. FYOBOC
'''

import pyvips

for j,i in enumerate(a.split('++++++++++++++++++')):
    dpi = 250
    text = i 
    text = text.replace('&', '&amp;')
    text = text.replace('<','&lt;')
    text = text.replace('>', '&gt;')
    image = pyvips.Image.text(text,  font='Arial', dpi=dpi, width=1080)
    image.write_to_file(f'Q{j+1}.png')

b = ''

for i in a.split('\n'):
  if  'ANSWERS' not in i:
      b += ''.join(i) + '\n'

!mkdir paper3
!mv *.png paper3

! tar cvf paper3.tar paper3

rm -rf paper3

c = '''If A and B can do a work in 12 days, B and C in 15 days, C and A in 20 days. If A, B and C work together, they will complete the work in how many days?
A.10		
B.12		
C.14
D.15
ANSWERS:A

A is thrice as efficient as B and therefore able to finish the work in 60 days less than B. How many days will B take to complete the work?
A.60		
B.90		
C.80
D.30
ANSWERS:B

An athlete runs 200 meters race in 24 sec. His speed in km/hr is:
A.25 km/hr	
B.12km/hr	
C.30 km/hr
D.32 km/hr
ANSWERS:C
       
A train is running at 54 km/hr. If it crosses a pole in 20sec, the length of the train is?
A.300m	
B.275m	
C.350m
D.200m
ANSWERS:A

If 75% of a number is added to 75, then the result is the number itself. The number is:
A.300		
B.400		
C.60
D.50
ANSWERS:A

The average of 5 numbers is 27. When one number is excluded, the average becomes 25. The excluded number is:
A.25		
B.27		
C.30
D.35
ANSWERS:D
       
A fruit seller had some apples. He sells 40% apples and still has 420 apples. Originally, he had:
A.700		
B.450		
C.600
D.440
ANSWERS:A

If the cost price of 16 pens is equal to the selling price of 12 pens, the gain percent is :
A.33.33%	
B.50%		
C.75%		
D.100%
ANSWERS:A

What percent of a day is 3 hrs?
A.12.5%	
B.16.66%	
C.18.66%
D.25%
ANSWERS:A

If the cost price is 50% of Selling price. Then what is the profit percent?
A.100%		
B.120%		
C.300%
D.150%
ANSWERS:A

The average of first 5 multiples of 10 is:
A.20	
B.30		
C.40
D.25
ANSWERS:B

A card is drawn from a pack of well shuffled cards. What is the probability of getting a face card?
A.1/26		
B.3/13		
C.1/4
D.5/13
ANSWERS:B
 
At what rate of interest per annum will a sum of money double in 16 years?
A.6.25%	
B.12%		
C.8%
D.10%
ANSWERS:A

A bag contains 6 black and 8 white balls. 1 ball is drawn at random. What is the probability that the ball drawn is white?
A.5/7		
B.4/7		
C.3/4
D.3/7
ANSWERS:B
       
A card is drawn from a pack of well shuffled cards. What is the probability of getting a red or a king card?
A.1/13		
B.9/13		
C.7/13
D.27/52
ANSWERS:C

If one-third of one-fourth of a number is 20,then three-tenth of that number is.
A.54		
B.92		
C.72
D.32
ANSWERS:C

Two numbers are respectively 20% and 50% more than a third number. The ratio of the two numbers is.
A.3:4		
B.8:7		
C.6:7
D.4:5
ANSWERS:D 

Which of the following is a prime number?
A.33		
B.81		
C.93
D.97
ANSWERS:D
       
In how many ways can the letters of the word AUCTION be arranged so that the vowels always come together?
A.120		
B.1440		
C.576
D.578
ANSWERS:C

A coin is tossed 3 times. What is the probability of getting atleast 2 heads?
A.1/2		
B.1/3		
C.1/4
D.2/3
ANSWERS:A

If A:B=5:9 and B:C=4:7, find A:B:C.
A.8:7:3		
B.16:81:91	
C.20:36:63
D.15:19:31
ANSWERS:C
       
An article when sold at a gain of 5% yields rs.15 more than when sold at a loss of 5%. Its cost price is:
A.125		
B.120		
C.720
D.150
ANSWERS:D

Some articles were bought at 6 articles for Rs. 5 and sold at 5 articles for Rs. 6. Gain percent is.
A.4%		
B.33%		
C.30%
D.25%
ANSWERS:A

The length of the bridge, which a train 130 meters long and travelling at 45 km/hr can cross in 30 seconds, is.
A.200m	
B.235m	
C.245m
D.250m
ANSWERS:C

A boat can travel with a speed of 13 km/hr in still water. If the speed of the stream is 4 km/hr, find the time taken by the boat to go 68 km downstream.
A.5hrs		
B.2hrs		
C.3hrs
D.4hrs
ANSWERS:D

A tank is filled in 5 hours by three pipes A, B and C. The pipe C is twice as fast as B and B is twice as fast as A. How much time will pipe A alone take to fill the tank?
A.35		
B.34		
C.36
D.20
ANSWERS:A

In what ratio must a shopkeeper mix two types of rice worth Rs.50/kg and Rs.70/kg, so that the average cost of the mixture is Rs.65/kg?
A.1:3		
B.3:1		
C.2:5
D.5:1
ANSWERS:A

If the price of an item is decreased by 10% and then increased by 10%, the net effect on the price of the item is:
A.1% decrease	
B.1% increase	
C.10% decrease
D.none
ANSWERS:A

Two successive discount of 10% and 20% are equivalent to a single discount of:
A.20%		
B.18%		
C.15%
D.28%
ANSWERS:D

Excluding stoppages, the speed of a bus is 54 kmph and including stoppages, it is 45 kmph. For how many minutes does the bus stop per hour?
A.9		
B.10		
C.12
D.20
ANSWERS:B

Six bells commence tolling together and toll at intervals of 2, 4, 6, 8 10 and 12 seconds respectively. In 30 minutes, how many times do they toll together?
A.16		
B.15		
C.20
D.11
ANSWERS:A


The average of 20 numbers is zero. Of them, at the most, how many may be greater than zero?
A.0		
B.1		
C.10
D.19
ANSWERS:D

Two friends, A & B had some candies each. One of them had 15 candies more than the other. The candies with A were 60% of the total candies with them. How many candies did each have?
A.40, 25	
B.47, 32	
C.45, 30
D.49, 34
ANSWERS:C

The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is.
A.15		
B.16		
C.18
D.25
ANSWERS:B

A train 125 m long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is.
A.45 km/hr	
B.50 km/hr	
C.54 km/hr
D.55 km/hr
ANSWERS:B
	
Some men can do a piece of work in 12 days. Two times the number of such men can do half of the same work in:
A.2 days	
B.5 days
C.3 days
D.6 days
ANSWERS:C

What is the probability of getting a sum 9 from two throws of a dice?
A.1/6		
B.1/8		
C.1/9
D.1/12	
ANSWERS:C

The sum of three numbers is 98. If the ratio of the first to second is 2 :3 and that of the second to the third is 5 : 8, then the second number is:
A.20		
B.30		
C.48
B.58
ANSWERS:B

Three unbiased coins are tossed. What is the probability of getting at most two heads?
A.3/4		
B.1/4		
C.3/8		
D.7/8
ANSWERS:D

Soni is 20 % heavier than Rekha in weight. By how much percent is Rekha lighter than Soni?
A.20%		
B.25%		
C.16.67%
D.None of these
ANSWERS:c

If MADRAS is written as NBESBT, the BOMBAY is written as:
A.CPNCBZ	
B.CPNCBX	
C.CPOCBZ
D.none
ANSWERS:A

In a certain code COMPUTER is written as RFUVQNPC. How is MEDICINE written in that code?
A.EOJDJJOE	
B.EOJDEJFM	
C.MFEDJJOE
D.none
ANSWERS:D
       
A man said to a woman, “Your mother’s husband’s sister is my aunt”. How is the woman related to 	the man?
A.daughter	
B.sister		
C.aunt
D.daughter in law
ANSWERS:B

Pointing to a photograph, Vipul said, “She is the daughter of my paternal grandfather’s only son.” How is Vipul related to the girl?
A.son		
B.brother	
C.cousin
D.grandson
ANSWERS:B

A girl introduced a boy as the son of the daughter of the father of her maternal uncle. The boy is girl’s:
A.brother	
B.uncle		
C.cousin
D.son
ANSWERS:A

Pointing to a photograph Lata says, "He is the son of the only son of my grandfather." How is the man in the photograph related to Lata?
A.Brother	
B.Uncle
C.Cousin
D.Data is inadequate
ANSWERS: D

Pointing to a woman, Abhijit said, "Her granddaughter is the only daughter of my brother." How is the woman related to Abhijit?
A. Sister		
B. Grandmother	
C. Sister-in-law
D. Mother
ANSWERS : D

If A is the brother of B; B is the sister of C; and C is the father of D, how D is related to A?
A. Brother	
B. Sister		
C. Nephew
D. Cannot be determined
ANSWERS : D

In a certain code, BOXER is written as AQWGQ. How VISIT is written in that code?
A. UKRKU	
B. UKRKS	
C. WKRKU
D. WKRKS
ANSWERS : B

If PAPER is written as OZODQ, how PENCIL can be written in that code?
A. QFODJM         
B. OFOBHM        
C. ODMDJM
D. ODMBHK
ANSWERS :D

Amit said - "This girl is the wife of the grandson of my mother". How is Amit related to the girl?
A. Brother             
B. father 	
C. Husband
D. Father-in-law
ANSWERS : D

In a certain code SOCIAL is written as TQFMFR, then how you will code DIMPLE?
A. EKPTQK             
B. EKPQPJ	
C. EKPSPJ
D. EKPSOH
ANSWERS : A
If LINGER is 123456 and FORCE is 56789, then FIERCE is
A. 345667              
B. 456678	
C. 345677
D. 556789
ANSWERS : B

As per the given information, how is G related to M?
A. Brother	
B. Father	
C. Father-in-law
D. Grandfather
ANSWERS : D

If N is married to Z, then how is Z related to L?
A. Son	
B. Can’t be determined		
C. Daughter
D. Brother-in-law
ANSWERS : B

As per the given information, how is I related to K?
A. Niece		
B. Son		
C. Daughter
D. Son-in-law
ANSWERS : B	

       
If in a certain language FASHION is coded as FOIHSAN. How is PROBLEM coded in that code?
A. ROBLEMP	
B. PELBORM	
C. PRBOELM
D. PELBRONR
ANSWERS : B


If in a certain language, ENTRY is coded as 12345 and STEADY is coded as 931785, then state which is the correct code for each of the given word.
TENANT
A. 956169	
B.196247 	
C.352123	
D.312723
ANSWERS : D

If in a certain language, ENTRY is coded as 12345 and STEADY is coded as 931785, then state which is the correct code for each of the given words.
NEATNESS
A.25196577	
B.21732199 	
C.21362199	
D.21823698
ANSWERS : B

If in a certain language, ENTRY is coded as 12345 and STEADY is coded as 931785, then state which is the correct code for each of the given words.
SEDATE
A.918731	
B. 954185	
C.814195	
D.614781
ANSWERS : A
'''

answers = {
    
 'A':1,

}
count = 1
for i in c.split('\n'):
  if 'ANSWERS' in i:
    print(count,',', i.split(':')[-1].strip().upper(), sep='')
    # print(count,',', i.split(':')[-1].strip() , sep='')

    count += 1

ord('A')

